### PR TITLE
feature/seo-images

### PR DESCRIPTION
**Pull request by hawkticehurst**
**Pull request recommendations:**
- [x] Name your pull request _your-development-type/short-description_. Ex: _feature/read-tiff-files_
- [ ] Link to any relevant issue in the PR description. Ex: _Resolves [gh-12], adds tiff file format support_
- [x] Provide context of changes.

Add SEO images created for the cookie-cutter to this repo.

- [ ] Provide relevant tests for your feature or bug fix.
- [ ] Provide or update documentation for any feature added by your pull request.

Thanks for contributing!

### CODE REVIEW

**Comment by evamaxfield** [comment]
Lemme debug this issue... The test is meant to print out a list of all the files contained in the generated `cdp-design` package and since this PR is adding files, I think we should check this one.

**Comment by evamaxfield** [comment]
Can you try updating your branch and pushing the merge commit. I updated the GH Actions trigger.

**Comment by hawkticehurst** [comment]
@JacksonMaxfield merged in changes from main.

**Comment by evamaxfield** [comment]
Did we want this file to be packaged up with the rest of these files? Looks like it isn't. I don't think we need it to be packaged -- you?

**Comment by hawkticehurst** [comment]
No, I don't think so. The SEO images are used in the cookie-cutter template and you had at one point said I should also put them in cdp-design as a sort of extra redundancy. For storage essentially.

**Comment by evamaxfield** [comment]
Cool. Merging then!

**Pull request merged**
